GREET = """This is a bot """


HELP = """Commands:
//help: Get help
//rules: Learn the rules of the game
//cards: List the different cards and their names
//lore: Learn the short lore of the game"""

RULES = """*How to play*
 Love Letter is played in a series of rounds. Each round represents one day. At the end of each round, one player’s letter reaches Princess Annette, and she reads it. When she reads enough letters from one suitor, she becomes enamored and grants that suitor permission to court her. That player wins the princess’s heart and the game. 
*Taking a turn*
On your turn, you draw a card from the deck and add it to your hand. Then choose one of the two cards in your hand and discard it. Apply any effect on the card you discarded. You must apply its effect, even if it is bad for you. See below for the effects and special cases of each individual card. All discarded cards remain in front of the player who discarded them. Overlap the cards so that it’s clear in which order they were discarded. This helps players to figure out which cards other players might be holding. Once you finish applying the card’s effect, the turn passes to the next player.
*Out of the round*
If a player is knocked out of the round, that player discards the card in his or her hand (do not apply the card’s effect) and takes no more turns until next round.
*End of a round*
A round ends if the deck is empty at the end of a turn. The royal residence closes for the evening, the person closest to the princess delivers the love letter, and Princess Annette retires to her chambers to read it. All players still in the round reveal their hands. The player with the highest ranked person wins the round. In case of a tie, the player who discarded the highest total value of cards wins. A round also ends if all players but one are out of the round, in which case the remaining player wins. The winner receives a token of affection. A new round begins after the previous one ends. The winner of the previous round goes first, because the princess speaks kindly of him or her at breakfast.
*Winning* A player wins the game after winning a number of tokens based on the number of players:
    • 2 Players 7 tokens 
    • 3 Players 5 tokens 
    • 4 players 4 tokens 
*The people*
The events of this game take place between the events of Courtier and Dominare, two other games in the Tempest line. Here are brief profiles of the people in the game. 
*8: Princess Annette*
Hampered only by the naïveté of youth, Princess Annette is elegant, charming, and beautiful. Obviously, you want the princess to carry your letter. However, she is self-conscious about matters of the heart, and if confronted, will toss your letter in the fire and deny ever seeing it. If you discard the Princess—no matter how or why—she has tossed your letter into the fire. You are knocked out of the round. 
*7: Countess Wilhelmina*
Always on the prowl for a handsome man or juicy gossip, Wilhelmina’s age and noble blood make her one of Princess Annette’s friends. While she has great influence over the princess, she makes herself scarce whenever the king or prince are around. Unlike other cards, which take effect when discarded, the text on the Countess applies while she is in your hand. In fact, she has no effect when you discard her. If you ever have the Countess and either the King or Prince in your hand, you must discard the Countess. You do not have to reveal the other card in your hand. Of course, you can also discard the Countess even if you do not have a royal family member in your hand. She likes to play mind games…
*6: King Arnaud IV*
The undisputed ruler of Tempest… for the moment. Because of his role in the arrest of Queen Marianna, he does not rate as highly with Princess Annette as a father should. He hopes to work himself back into her graces. When you discard King Arnaud IV, trade the card in your hand with the card held by another player of your choice. You cannot trade with a player who is out of the round, nor with someone protected by the Handmaid. If all other players still in the round are protected by the Handmaid, this card does nothing. 
*5: Prince Arnaud*
As a social gadfly, Prince Arnaud was not as distressed over his mother’s arrest as one would suppose. Since many women clamor for his attention, he hopes to help his sister find the same banal happiness by playing the matchmaker. When you discard Prince Arnaud, choose one player still in the round (including yourself). That player discards his or her hand (do not apply its effect) and draws a new card. If the deck is empty, that player draws the card that was removed at the start of the round. If all other players are protected by the Handmaid, you must choose yourself. 
*4: Handmaid Susannah*
Few would trust a handmaid with a letter of importance. Fewer still understand Susannah’s cleverness, or her skilled ability at playing the foolish handmaid. That the queen’s confidante and loyal servant escaped any attention after the queen’s arrest is a testament to her clever mind. When you discard the Handmaid, you are immune to the effects of other players’ cards until the start of your next turn. If all players other than the player whose turn it is are protected by Susannah, the player must choose him- or herself if possible. 
*3: Baron Talus*
The scion of an esteemed house that has long been a close ally of the royal family, Baron Talus has a quiet and gentle demeanor that conceals a man used to being obeyed. His suggestions are treated as if they came from the king himself. When discarded, choose one other player still in the round. You and that player secretly compare your hands. The player with the lower rank is knocked out of the round. In case of a tie, nothing happens. If all other players still in the round are protected by the Handmaid, this card does nothing. 
*2: Priest Tomas*
Open, honest, and uplifting, Father Tomas always seeks out the opportunity to do good. With the arrest of the queen, he is often seen about the palace, acting as confessor, counselor, and friend. When you discard the Priest, you can look at one other player’s hand. Do not reveal the hand to all players. 
*1: Guard Odette*
Charged with seeing to the security of the royal family, Odette follows her orders with persistence and diligence… even though her mentor is said to have drowned while fleeing arrest for complicity in the queen’s treason. When you discard the Guard, choose a player and name a card (other than Guard). If that player has that card, that player is knocked out of the round. If all other players still in the round are protected by the Handmaid, this card does nothing."""

LORE = """The guard looked Bartolemew Kaiss up and down for a moment and then frowned. “I’m sorry, Master Kaiss, but the princess is not seeing visitors at this time. She is, of course, in despair over the arrest of her mother.” “Of course,” the young composer said, nodding and looking appropriately sympathetic. “But I am not just visiting, you see. Her Highness requested my instruction. We are to practice her singing.” “The princess already has a vocal maestro,” the gruff woman replied, raising an eyebrow. “I’m sure he knows that, Odette,” said a kind voice echoing down the hall that connected the residence to the palace. The two turned to see Susannah, one of Princess Annette’s handmaids, walking toward them. “What the good composer means to say is that Annette requested his work for their practice.” The young woman smiled at the guard and gave Bartolemew a conspiratorial wink. From his satchel, Bartolemew produced a sealed tube. “If you will be so kind as to deliver these sheets of music, my dear Susannah,” he said with a smile and a genteel nod. The guard took the tube from him, but as it changed hands, something with a little weight shifted inside the tube. “What’s this, then?” the guard asked, jostling it next to her ear. _Certainly not a small statue of a bird the Princess is so fond of_, Bartolemew thought. “The… quill and ink I used to pen the music, in case she or the maestro wish to make any changes. I always deliver some with a new composition.” Susannah gently took the case from the suspicious guard. “Oh, would you stop, Odette? It’s just some music,” she chided playfully. “I’ll see to it that milady gets these,” she added with a hand on Bartolemew’s arm. “I’m sure she’ll be eager to see the contents.”
*Object*
In the wake of the arrest of Queen Marianna for high treason, none was more heartbroken than her daughter, Princess Annette. Suitors throughout the CityState of Tempest sought to ease Annette’s sorrow by courting her to bring some joy into her life. You are one of these suitors, trying to get your love letter to the princess. Unfortunately, she has locked herself in the palace, so you must rely on intermediaries to carry your message. During the game, you hold one secret card in your hand. This is who currently carries your message of love for the princess. Make sure that the person closest to the princess holds your love letter at the end of the day, so it reaches her first!"""

